name: PHPStan

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    
    runs-on: ubuntu-latest
    
    steps:
        - name: "Checkout"
          uses: actions/checkout@v2

        - name: PHPStan VERSION
          uses: docker://oskarstark/phpstan-ga
          with:
            args: --version

        - name: PHPStan
          uses: docker://oskarstark/phpstan-ga
          with:
              args: analyze src/ --level=5
