name: PHPStan MANUAL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu-latest, windows-latest, macos-latest ]
        #php: [ '5.6', '7.0','7.1','7.2', '7.4', '8.0' ]
        php: [ '7.1', '7.2', '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      #- name: Cache Composer packages
      #  id: composer-cache
      #  uses: actions/cache@v2
      #  with:
      #    path: vendor
      #    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      #    restore-keys: |
      #      ${{ runner.os }}-php-

      - name: Install dependencies
        #if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: php version
        run: php --version

      - name: phpstan version
        run: php vendor/bin/phpstan.phar --version

      - name: Run phpstan
        run: php vendor/bin/phpstan.phar analyse -c phpstan.neon

